---

- name: FLUENTD ON DEBIAN | Install prerequisites
  package:
    name:
      - python3-software-properties
      - apt-transport-https
    state: present

- name: FLUENTD ON DEBIAN | Import key
  apt_key:
    url: "{{ fluentd_apt_key }}"
    state: present

- name: FLUENTD ON DEBIAN | Add repository
  apt_repository:
    repo: "{{ fluentd_apt_repository }}"
    state: present
